// <auto-generated />
namespace UMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddTableProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTableProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271401474_AddTableProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
